[package]
name = "nyson-setup"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.38"
fltk = { version = "^1", features = ["fltk-bundled"] }
serde_json = "1.0.64"
which = "4.1.0"
